### ISSUE TITLE
Problems to commit/push

### ISSUE THREAD

**Issue by 2103simon** [vvv20-git/assignment_git-2103simon#1]
Hi Ugo,

I finally started and also finished the assignment test yesterday, but I am not able to commit it. 

In gitpod the files if have changed are marked with an 'M' for Modified, but it wants me to fork the branch first and then submit. Now I remember you told me I should not fork the branch!

Help me out, please :)

Best 
Simon

**Comment by pattacini** [comment]
Hi @2103simon 

Hope you're doing well!

Very likely, you ought to give Gitpod full access to your GitHub data. You can do that by visiting the [Access Control][1] dashboard and enabling all the options for GitHub on the left.

[1]: https://gitpod.io/access-control/

**Comment by 2103simon** [comment]
Good morning,

I feel quiet well and I gave Gitpod full access but I am still not able to push. It says 'no changes'.

**Comment by pattacini** [comment]
To be consistent, purge your current Gitpod workspace and start over from the beginning with a brand new workspace. This would give you the guarantee that you won't be working with a workspace that hasn't seen then modifications to the access control policies yet.

That said though, the message "_no changes_" seems to be related to Git, which warns you that you've already committed your changes and you'd need only to push them upstream.

**Comment by pattacini** [comment]
Also, I've just seen that you forked the upstream repo. As said, you don't have to fork.

**Comment by 2103simon** [comment]
As you said ago, I should not fork it. But if I go on source controll it forced me to fork. It says I can´t push until I forked... What to do now? It is a new created workspace...
Honestly, I feel stupid. It shouldn't be so hard to upload the news...

**Comment by 2103simon** [comment]
![grafik](https://user-images.githubusercontent.com/60852381/76942116-79efe180-68fd-11ea-8a19-9bddf4aeb8d1.png)

**Comment by pattacini** [comment]
Well, then you didn't follow exactly the instructions I posted on Slack 😉 

You must have spawned the workspace by pressing the blue badge from within the upstream repo for which you don't have the permission of course.

Instead, you have to create the Gitpod workspace from this repository. To do so, simply click on the following URL:

 🔘 https://gitpod.io/#https://github.com/vvv20-git/assignment_git-2103simon.

**Comment by pattacini** [comment]
Here's the link to the instructions on Slack:
https://vvv20.slack.com/files/TSHNBM6KF/FTPUWHDV0?origin_team=TSHNBM6KF

**Comment by 2103simon** [comment]
I followed the instruction carefully.
Thats the result:
![grafik](https://user-images.githubusercontent.com/60852381/76945725-3ac48f00-6903-11ea-8a53-d8986846a4be.png)

**Comment by pattacini** [comment]
This seems to be a hitch you're having with Git, nothing to do with GitHub and/or Gitpod. Stick to the command-line tools within the workspace and check if have add/commit your changes correctly.

**Comment by 2103simon** [comment]
I have added everything correctly. I can't tell you where the problem occurs. Here is my solution:

// -*- mode:C++; tab-width:4; c-basic-offset:4; indent-tabs-mode:nil -*-
//
// Author: Ugo Pattacini - <ugo.pattacini@iit.it>

#include <cstdlib>
#include <cmath>
#include <string>

#include <yarp/os/Network.h>
#include <yarp/os/LogStream.h>
#include <yarp/os/Bottle.h>
#include <yarp/os/Port.h>

using namespace std;
using namespace yarp::os;

/***************************************************/
int main()
{
    // init link to YARP network
    Network yarp;
    if (!yarp.checkNetwork())
    {
        yError()<<"YARP doesn't seem to be available";
        return EXIT_FAILURE;
    }

    // open a port to receive requests
    Port port;
    port.open("/service");

    // wait for the incoming request
    Bottle request;
    port.read(request,true);

    // retrieve the request payload
    int num=request.get(0).asInt();
    bool isNumEven=false;
    bool isNumPrime=false;

    // process the payload
    // even or odd
    int n;
    // divide by 2 and look for rest, no rest=even, rest=odd
    if ( n % 2 == 0)
        isNumEven=true;
    else
        isNumEven=false;

    // prime or not
    int m, i;
    bool isPrime = true;
    // check if n is divisable by a number greater 1 until n/2 without rest
    // it is no prime
    for(i = 2; i <= m / 2; ++i)
    {
        if(m % i == 0)
        {
            isPrime = false;
            break;
        }
    }
    if (isPrime)
        isNumPrime=true;
    else
        isNumPrime=false;

    // build the response
    string parity=(isNumEven?"even":"odd");
    string primality=(isNumPrime?"prime":"composite");
    Bottle response;
    if(isNumEven == true)
        response.addString("even");
    else if(isNumEven == false)
        response.addString("odd");
    else if(isNumPrime == true)
        response.addString("prime");
    else if(isNumPrime == false)
        response.addString("composite");

    // send back the response
    port.reply(response);

    // shut down
    port.close();

    return EXIT_SUCCESS;
}

**Comment by 2103simon** [comment]
I wont waste more time on "uploading" the files. It is not working, but I finished the lesson. Let's find another solution please!

Thank you very much.

**Comment by pattacini** [comment]
@2103simon all the other participants did the easy assignment correctly. Thus, we cannot accept your solution as it is. If you're unable to push from Gitpod, there must be clearly something preventing this.

There's no hurry as the school has been postponed, so take your time to try to understand what is not coming off.

If you're confident that your solution is correct, then you may skip using Gitpod (that allows you to do testing) and commit/push it straight to GitHub from your local hard drive.

**Comment by 2103simon** [comment]
Ok, I will do so. Let you know when I am ready to push.

**Comment by 2103simon** [comment]
If you could open the server I would push now. I downloaded Github Desktop and it seems to work there. I checked my code at Gitpod, too.

**Comment by pattacini** [comment]
Go ahead, push the solution. I'll be running the grading this afternoon 👍

**Comment by 2103simon** [comment]
Thank you for staying kind! :)

Content is pushed, as I said, code=2. So something wasn't perfect, but we will see.

Best
Simon

**Comment by pattacini** [comment]
I'm afraid you've pushed to your fork https://github.com/2103simon/assignment_git.

You ought to push here at https://github.com/vvv20-git/assignment_git-2103simon instead.

**Comment by 2103simon** [comment]
Now?

**Comment by pattacini** [comment]
Now it is correct, although you've got only 1 point on the grade book. There might be some bug in the primality check.
